### ISSUE TITLE
webthree build failed

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/webthree#10]
/webthree/build$ make
[ 11%] Building CXX object src/libwebthree/CMakeFiles/webthree.dir/WebThree.cpp.o
In file included from /home/ubuntu/webthree/src/libwebthree/WebThree.cpp:22:0:
/home/ubuntu/webthree/src/libwebthree/WebThree.h:30:31: fatal error: libdevcore/Common.h: No such file or directory
 #include <libdevcore/Common.h>
                               ^
compilation terminated.
make[2]: **\* [src/libwebthree/CMakeFiles/webthree.dir/WebThree.cpp.o] Error 1
make[1]: **\* [src/libwebthree/CMakeFiles/webthree.dir/all] Error 2
make: **\* [all] Error 2

**Comment by LefterisJP** [comment]
Is still still happening for you? Have you cloned the repository in the same directory as `cpp-ethereum` and `cpp-ethereum-cmake`, like the [Build Guide](https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu) points out?
