### ISSUE TITLE
eth with gethattach console interaction

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree#136]
running latest eth with latest geth attach 
Following commands displayed in geth console and some of them described at https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console though it seems a lot of commands not supported by eth and also there are commands in geth console that are not described in the reference. 

**admin**
=>datadir FAIL
{
    code: -32601,
    message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
  }

=> nodeInfo  OK
=> peers     OK
=> addPeer   OK
=> exportChain  FAIL
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x690b43]
**GO console crashed !!!**

=> getContractInfo() FAIL
{
    code: -32601,
    message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
  }

=> getDatadir() FAIL
returns undefined
unclear how to use it from console

=> getNodeInfo() FAIL
returns undefined
unclear how to use it from console

=> getPeers(callback) FAIL
returns undefined
unclear how to use it from console

=> httpGet (a,b)
usage is unclear (no go wiki)
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> importChain FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> register(address, contractaddress, contenthash) FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> registerUrl(address, contractaddress, contenthash) FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}   

=> saveInfo (contract.info, filename) FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}   

=> setGlobalRegistrar (a,b)
usage is unclear (no go wiki)
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}   

=> setHashReg(a,b) FAIL 
usage is unclear (no go wiki)
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}   

=> setSolc (pathtosolc) FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}   

=> setUrlHint (a,b) FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> sleep (seconds) OK  //the only function so far that prints help on how to use it from console!

=> sleepBlocks (a[,b]) OK 

=> startNatSpec() FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> startRPC (host, portNumber, corsheader, modules) FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> startWS(a,b,c,d) FAIL
usage is unclear (no go wiki)
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> stopNatSpec() FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> stopRPC() FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

=> stopWS() FAIL
{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available on this server"
}

**Comment by bobsummerwill** [comment]
This was the "need a newer geth version" issue, right?

**Comment by chriseth** [comment]
the issue moved to webthree-umbrella
