### ISSUE TITLE
mining - ethminer "no gpu device with sufficient memory was found"

### ISSUE THREAD

**Issue by professor-cowboy** [ethereum/webthree#145]
Can't get ethminer started with GPU mining.

Running geth node
loading ethminer -g
gets this error message: "no gpu device with sufficient memory was found. Can't GPU mine. Remove the -G argument"

I have a AMD Firepro w7100. It's a powerful graphics card with lots of memory

**Comment by luclu** [comment]
8GB surely is enough.
Did you try different graphic-drivers? If on gnu/linux proprietary and open-source ones?

**Comment by bobsummerwill** [comment]
Please do try the http://github.com/Genoil/cpp-ethereum miner, @misternils.

See https://gitter.im/ethereum/cpp-ethereum?at=5757286b970521a45839d36e

**Comment by bobsummerwill** [comment]
Just going to close this.   We're moving our repositories around, the right resolution for the time being is "please use Genoil ethminer" :-)
