### ISSUE TITLE
unable to transact using web3,js

### ISSUE THREAD

**Issue by yann300** [ethereum/webthree#44]
contract.set(345, "test")
where
function set(uint _i, string _s)
{
    i = _i;
    s = _s;
}

gives
web3.js - line 3772 - Uncaught invalid address

**Comment by debris** [comment]
same as https://github.com/ethereum/web3.js/issues/319

**Comment by makoto** [comment]
@debris @frozeman aren't both issues referencing each other? I am getting same error message when I simply follow the Mix tutorial at https://github.com/ethereum/wiki/wiki/Mix:-The-DApp-IDE .
