### ISSUE TITLE
JSRemoteConsole not included in eth/main.cpp

### ISSUE THREAD

**Issue by anthony-cros** [ethereum/webthree#69]
[`JSRemoteConsole`](https://github.com/ethereum/webthree/blob/de2bfa3/eth/main.cpp#L835) may not have been included due to [this directive](https://github.com/ethereum/webthree/blob/de2bfa3/eth/main.cpp#L45) (and sure enough it happened to me!)

I used [this workaround](https://github.com/doublethinkco/webthree-umbrella-cross/blob/master/cross-build/ethereum/webthree.sh#L34) for the time being (basically commenting out the corresponding block)

EDIT: updated link (workaround has moved since)

**Comment by bobsummerwill** [comment]
There is a pull request for this now:

https://github.com/ethereum/webthree/pull/89.

Please could you close this issue, @anthony-cros?   Thanks!

**Comment by anthony-cros** [comment]
Great, so I'll remove the corresponding hacks on our side then I guess?

**Comment by bobsummerwill** [comment]
Yes, we can :-)   Thanks!

**Comment by anthony-cros** [comment]
[done](https://github.com/doublethinkco/webthree-umbrella-cross/commit/2c065e5d32ec2891b8447503e5859e62b5edeebc) :)

**Comment by bobsummerwill** [comment]
Thanks!
