### ISSUE TITLE
GPU --opencl-devices option

### ISSUE THREAD

**Issue by tcoyze** [ethereum/webthree#79]
When attempting to mine on my Mac and specify '--opencl-devices 1' I am attempting to use my NVIDIA GPU not the integrated Intel Iris Pro. However, it keeps reverting to the Iris Pro which is device 0.

eth --frontier -b -i --list-devices output:

[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Iris Pro
    CL_DEVICE_TYPE: GPU
    CL_DEVICE_GLOBAL_MEM_SIZE: 1610612736
    CL_DEVICE_MAX_MEM_ALLOC_SIZE: 402653184
    CL_DEVICE_MAX_WORK_GROUP_SIZE: 512
[1] GeForce GT 750M
    CL_DEVICE_TYPE: GPU
    CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
    CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536870912
    CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

Command: eth --frontier -b --genesis genesis/genesis.json -i -m on -G --opencl-device 1
Output:
(++)Ethereum
Beware. You're entering the Frontier!
[OPENCL]:Found suitable OpenCL device [Iris Pro] with 1610612736 bytes of GPU memory

But I want the GeForce GT 750M not Iris Pro.

Device: Mac MGXC2LL/A El Capitan 10.11.1

**Comment by it4ch1** [comment]
same problem

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/webthree-umbrella/issues/272.
