### ISSUE TITLE
shh topics are formated differently

### ISSUE THREAD

**Issue by simon-jentzsch** [ethereum/webthree#81]
when posting a whisper-message like:

```
web3.shh.post({
 "topics": [ "0xad5e5a5bc4654dbef0d5cabd7abeb426769c073a" ],
 "payload": [ web3.fromAscii("open") ],
});
```

the inputPostFormatter-function will convert each topic to hex(

```
 post.topics = post.topics.map(function(topic){
    return utils.fromUtf8(topic);
});
```

)

But if I listen to the exact same topic like:

```
web3.shh.filter({ 
   'topics': [ "0xad5e5a5bc4654dbef0d5cabd7abeb426769c073a" ] 
}).watch(function(error,m) {
    // do something, but he never hits this line.
});
```

It is not converted.

The result: the topics don't match and I will never receive this message!

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/webthree-umbrella/issues/340.
